# Generated by Django 4.2.16 on 2026-05-22 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaikuanUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=15, unique=True, verbose_name="手机号"),
                ),
                (
                    "password_hash",
                    models.CharField(max_length=256, verbose_name="密码哈希"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "超级管理员"),
                            ("manager", "经理"),
                            ("operator", "操作员"),
                            ("viewer", "查看员"),
                        ],
                        default="viewer",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "departments",
                    models.JSONField(default=list, verbose_name="负责部门"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "排款用户",
                "db_table": "paikuan_users",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="部门"
                    ),
                ),
                (
                    "approval_number",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="审批单号"
                    ),
                ),
                ("project_desc", models.TextField(verbose_name="付款事项描述")),
                ("payee", models.CharField(max_length=200, verbose_name="收款方")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="计划总金额"
                    ),
                ),
                (
                    "planned_date",
                    models.DateField(db_index=True, verbose_name="计划付款日期"),
                ),
                (
                    "pay1_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="第1次付款日期"
                    ),
                ),
                (
                    "pay1_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="第1次付款金额",
                    ),
                ),
                (
                    "pay2_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="第2次付款日期"
                    ),
                ),
                (
                    "pay2_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="第2次付款金额",
                    ),
                ),
                (
                    "pay3_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="第3次付款日期"
                    ),
                ),
                (
                    "pay3_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="第3次付款金额",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "排款记录",
                "db_table": "paikuan_payments",
                "ordering": ["-planned_date", "-created_at"],
            },
        ),
    ]
