# Generated by Django 4.2.16 on 2026-05-23 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paikuanuser",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审批时间"),
        ),
        migrations.AddField(
            model_name="paikuanuser",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_users",
                to="paikuan.paikuanuser",
            ),
        ),
        migrations.AddField(
            model_name="paikuanuser",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="是否已审批"),
        ),
        migrations.AddField(
            model_name="paikuanuser",
            name="job_title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cashier", "出纳"),
                    ("finance_bp", "财务BP"),
                    ("finance_director", "财务总监"),
                ],
                default="",
                max_length=30,
                verbose_name="职务",
            ),
        ),
    ]
