# Generated by Django 4.2.16 on 2026-05-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0002_add_job_title_and_approval"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=30, unique=True, verbose_name="职务"),
                ),
                ("config", models.JSONField(default=dict, verbose_name="权限配置")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "职务权限",
                "db_table": "paikuan_job_permissions",
            },
        ),
        migrations.AlterField(
            model_name="paikuanuser",
            name="job_title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("finance_director", "财务总监"),
                    ("finance_bp", "财务BP"),
                    ("chief_cashier", "总出纳"),
                    ("cashier", "出纳"),
                ],
                default="",
                max_length=30,
                verbose_name="职务",
            ),
        ),
    ]
