# Generated by Django 4.2.16 on 2026-05-28 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0004_approvalrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_payments",
                to="paikuan.paikuanuser",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="approval_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=100,
                verbose_name="审批单号",
            ),
        ),
        migrations.CreateModel(
            name="PaymentChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id_snapshot",
                    models.IntegerField(db_index=True, verbose_name="排款ID快照"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "新建"),
                            ("update", "修改"),
                            ("delete", "删除"),
                        ],
                        max_length=10,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "operator_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="操作人姓名",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="字段名"
                    ),
                ),
                (
                    "field_label",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="字段中文名"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(blank=True, default="", verbose_name="修改前"),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, default="", verbose_name="修改后"),
                ),
                (
                    "at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="操作时间"
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_changes",
                        to="paikuan.paikuanuser",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="paikuan.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "排款变更日志",
                "db_table": "paikuan_payment_change_logs",
                "ordering": ["-at"],
                "indexes": [
                    models.Index(
                        fields=["payment", "at"], name="paikuan_pay_payment_84518c_idx"
                    )
                ],
            },
        ),
    ]
