# Generated by Django 4.2.16 on 2026-05-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0005_payment_updated_by_alter_payment_approval_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paikuanuser",
            name="job_title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("finance_director", "财务总监"),
                    ("finance_bp", "财务BP"),
                    ("chief_cashier", "总出纳"),
                    ("cashier", "出纳"),
                    ("general_manager", "总经理"),
                    ("gm_assistant", "总经理助理"),
                    ("settlement_accountant", "结算会计"),
                ],
                default="",
                max_length=30,
                verbose_name="职务",
            ),
        ),
    ]
