# Generated by Django 4.2.16 on 2026-05-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0006_alter_paikuanuser_job_title"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("approval_number", ""), _negated=True),
                fields=(
                    "department",
                    "approval_number",
                    "payee",
                    "planned_date",
                    "total_amount",
                ),
                name="uniq_payment_business_key",
            ),
        ),
    ]
