# Generated by Django 4.2.16 on 2026-05-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0008_payment_plan_adjustment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="plan_adjustment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="计划调整金额",
            ),
        ),
    ]
