# Generated by Django 4.2.16 on 2026-06-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0009_alter_payment_plan_adjustment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="project_no",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=20,
                verbose_name="项目编号",
            ),
        ),
    ]
