# Generated by Django 4.2.16 on 2026-06-02 17:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0010_payment_project_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="prepaid_offset_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=15,
                verbose_name="预付核销冲抵金额",
            ),
        ),
    ]
