# Generated by Django 4.2.16 on 2026-06-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0011_payment_prepaid_offset_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="applicant",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=100,
                verbose_name="申请人",
            ),
        ),
    ]
