# Generated by Django 4.2.16 on 2026-06-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0013_payment_installments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentinstallment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
