# Generated by Django 4.2.16 on 2026-06-10 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0014_alter_paymentinstallment_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=100,
                        verbose_name="操作人",
                    ),
                ),
                ("method", models.CharField(max_length=8, verbose_name="方法")),
                (
                    "path",
                    models.CharField(
                        db_index=True, max_length=300, verbose_name="接口路径"
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=20,
                        verbose_name="模块",
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(default=0, verbose_name="响应状态码"),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="请求参数（已脱敏）"
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="来源IP"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作审计日志",
                "db_table": "paikuan_audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_name", "created_at"],
                        name="paikuan_aud_user_na_83a535_idx",
                    ),
                    models.Index(
                        fields=["module", "created_at"],
                        name="paikuan_aud_module_c39dbd_idx",
                    ),
                ],
            },
        ),
    ]
