# Generated by Django 4.2.16 on 2026-06-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0015_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="paikuanuser",
            name="pwd_changed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="密码修改时间"
            ),
        ),
    ]
