# Generated by Django 4.2.16 on 2026-06-10 14:35

from django.db import migrations, models


def renumber_duplicate_seqs(apps, schema_editor):
    """历史数据兜底：早期版本的分期 seq 可能默认 0 重复。
    按 (seq, pay_date, id) 顺序为每条排款的分期重排 1..n，再加唯一约束才不会失败。
    API 写入一直是整组重排（_save_installments），新数据天然满足约束。"""
    PaymentInstallment = apps.get_model('paikuan', 'PaymentInstallment')
    from collections import defaultdict
    by_payment = defaultdict(list)
    for row in (PaymentInstallment.objects
                .order_by('payment_id', 'seq', 'pay_date', 'id')
                .only('id', 'payment_id', 'seq').iterator()):
        by_payment[row.payment_id].append(row)
    for rows in by_payment.values():
        seqs = [r.seq for r in rows]
        if len(set(seqs)) == len(seqs) and all(s >= 1 for s in seqs):
            continue
        for i, r in enumerate(rows, 1):
            if r.seq != i:
                r.seq = i
                r.save(update_fields=['seq'])


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0016_paikuanuser_pwd_changed_at"),
    ]

    operations = [
        migrations.RunPython(renumber_duplicate_seqs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="paymentinstallment",
            constraint=models.UniqueConstraint(
                fields=("payment", "seq"), name="uniq_installment_seq_per_payment"
            ),
        ),
    ]
