# Generated by Django 4.2.16 on 2026-06-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0017_paymentinstallment_uniq_installment_seq_per_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrecord",
            name="project_short_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=100,
                verbose_name="项目简称",
            ),
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="secondary_dept",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=100,
                verbose_name="二级部门",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="project_short_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=100,
                verbose_name="项目简称",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="secondary_dept",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=100,
                verbose_name="二级部门",
            ),
        ),
    ]
