# Generated by Django 4.2.16 on 2026-06-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0018_approvalrecord_project_short_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrecord",
            name="scheduled_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="已排款金额"
            ),
        ),
    ]
