# Generated by Django 4.2.16 on 2026-06-12 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0020_backfill_scheduled_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="paikuan.approvalrecord",
                verbose_name="来源审批",
            ),
        ),
        migrations.CreateModel(
            name="PaymentPlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seq",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=1, verbose_name="批次序号"
                    ),
                ),
                (
                    "planned_date",
                    models.DateField(db_index=True, verbose_name="计划日期"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="计划金额"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="备注"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_items",
                        to="paikuan.payment",
                    ),
                ),
            ],
            options={
                "db_table": "paikuan_payment_plan_items",
                "ordering": ["payment", "seq"],
                "indexes": [
                    models.Index(
                        fields=["payment", "planned_date"],
                        name="paikuan_pay_payment_2c1e88_idx",
                    )
                ],
            },
        ),
    ]
