# Generated by Django 4.2.16 on 2026-06-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0023_link_historical_approvals"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrecord",
            name="g7_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=21,
                verbose_name="G7编号",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="g7_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=21,
                verbose_name="G7编号",
            ),
        ),
    ]
