# Generated by Django 4.2.16 on 2026-06-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0024_add_g7_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="paikuanuser",
            name="must_change_password",
            field=models.BooleanField(default=False, verbose_name="需强制改密"),
        ),
    ]
