# Generated by Django 4.2.16 on 2026-06-23 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0025_add_must_change_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="方案名称")),
                (
                    "module",
                    models.CharField(
                        db_index=True, max_length=40, verbose_name="所属列表"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("private", "私有"), ("public", "公共")],
                        db_index=True,
                        default="private",
                        max_length=10,
                        verbose_name="可见范围",
                    ),
                ),
                (
                    "payload",
                    models.TextField(
                        blank=True, default="{}", verbose_name="状态快照(JSON)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="list_schemes",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "pk_list_schemes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ListSchemeDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        db_index=True, max_length=40, verbose_name="所属列表"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_of",
                        to="paikuan.listscheme",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_scheme_defaults",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "pk_list_scheme_defaults",
                "unique_together": {("user", "module")},
            },
        ),
        migrations.AddIndex(
            model_name="listscheme",
            index=models.Index(
                fields=["module", "scope"], name="pk_list_sch_module_888028_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listscheme",
            index=models.Index(
                fields=["owner", "module"], name="pk_list_sch_owner_i_455bb7_idx"
            ),
        ),
    ]
