# Generated by Django 4.2.16 on 2026-06-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0026_listscheme_listschemedefault_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrecord",
            name="ext_bill_no",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="外部对账单号",
            ),
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="ext_raw",
            field=models.JSONField(blank=True, default=dict, verbose_name="外部原始行"),
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="ext_source",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=20,
                verbose_name="外部来源",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ext_bill_no", ""), _negated=True),
                fields=("ext_source", "ext_bill_no"),
                name="uniq_approval_ext_bill_no",
            ),
        ),
    ]
