# Generated by Django 4.2.16 on 2026-06-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0027_approvalrecord_ext_bill_no_approvalrecord_ext_raw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrecord",
            name="notes",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="备注"
            ),
        ),
    ]
