# Generated by Django 4.2.16 on 2026-06-26 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0028_approvalrecord_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrecord",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="软删除时间"
            ),
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_approval_records",
                to="paikuan.paikuanuser",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="软删除时间"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_payments",
                to="paikuan.paikuanuser",
            ),
        ),
    ]
