# Generated by Django 4.2.16 on 2026-06-26 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0029_soft_delete_payment_approval"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("approvals", "审批记录"),
                            ("payments", "排款记录"),
                            ("transport", "运输对账单"),
                        ],
                        max_length=20,
                        verbose_name="导出类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "排队中"),
                            ("running", "生成中"),
                            ("done", "已完成"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                        verbose_name="状态",
                    ),
                ),
                (
                    "params",
                    models.JSONField(blank=True, default=dict, verbose_name="筛选参数"),
                ),
                (
                    "filename",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="文件名"
                    ),
                ),
                (
                    "file_data",
                    models.BinaryField(blank=True, null=True, verbose_name="文件字节"),
                ),
                ("row_count", models.IntegerField(default=0, verbose_name="导出行数")),
                (
                    "error",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "pk_export_jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
