# Generated by Django 4.2.16 on 2026-06-30 04:00

from decimal import Decimal

from django.db import migrations, models


def _key_for(p):
    """与 Payment.compute_dedup_key 同口径（迁移内不可调用模型方法，复制逻辑）。"""
    no = p.approval_number or ''
    if not no or set(no) == {'0'} or p.deleted_at is not None:
        return None
    try:
        amt = Decimal(str(p.total_amount)).quantize(Decimal('0.01'))
    except Exception:
        amt = p.total_amount
    return '|'.join([p.department or '', no, p.payee or '',
                     str(p.planned_date or ''), str(amt)])


def backfill_dedup_key(apps, schema_editor):
    """回填存量行的 dedup_key。防御性「先到先得」：同一 key 仅首行保留，
    其余保持 NULL —— 这样即便历史数据本就存在重复业务键（生产 MySQL 上条件唯一
    索引从未真正建出，存量可能有重复），后续 AddConstraint 也不会失败。"""
    Payment = apps.get_model('paikuan', 'Payment')
    seen = set()
    batch = []
    for p in Payment.objects.all().iterator():
        key = _key_for(p)
        if key is None or key in seen:
            continue
        seen.add(key)
        p.dedup_key = key
        batch.append(p)
        if len(batch) >= 500:
            Payment.objects.bulk_update(batch, ['dedup_key'])
            batch = []
    if batch:
        Payment.objects.bulk_update(batch, ['dedup_key'])


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0030_export_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="dedup_key",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="业务去重键"
            ),
        ),
        # 先回填存量（去重后），再加唯一约束，避免历史重复键导致约束创建失败。
        migrations.RunPython(backfill_dedup_key, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("dedup_key",), name="uniq_payment_dedup_key"
            ),
        ),
        # 移除被取代的历史条件唯一约束（SQLite/PG 上真实存在，MySQL 上本就为空操作）。
        migrations.RemoveConstraint(
            model_name="payment",
            name="uniq_payment_business_key",
        ),
    ]
