# Generated by Django 4.2.16 on 2026-06-26 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0030_export_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dept",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=100,
                        verbose_name="关联事业部",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("approval_pending", "待审批"),
                            ("schedule_pending", "待排款"),
                            ("payment_due", "今日到期"),
                            ("overdue", "逾期未付"),
                            ("budget_alert", "超预算预警"),
                            ("prepaid_pending", "预付待核销"),
                            ("system", "系统消息"),
                        ],
                        db_index=True,
                        max_length=24,
                        verbose_name="类型",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "提示"),
                            ("warn", "提醒"),
                            ("danger", "预警"),
                        ],
                        default="info",
                        max_length=8,
                        verbose_name="级别",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "body",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="内容"
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="跳转链接"
                    ),
                ),
                (
                    "dedup_key",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="去重键"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="已读"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="已读时间"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "pk_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="pk_notifica_recipie_72de07_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("recipient", "dedup_key"),
                name="uniq_notification_recipient_dedup",
            ),
        ),
    ]
