# Generated by Django 4.2.16 on 2026-06-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0031_payment_dedup_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_priority",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="重点付款"
            ),
        ),
    ]
