# Generated by Django 4.2.16 on 2026-07-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0032_payment_is_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalrecord",
            name="g7_number",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="G7编号"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="g7_number",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="G7编号"
            ),
        ),
    ]
