# Generated by Django 4.2.16 on 2026-07-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0033_alter_approvalrecord_g7_number_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["deleted_at", "planned_date"], name="pay_active_planned_idx"
            ),
        ),
    ]
