# Generated by Django 4.2.16 on 2026-07-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0034_payment_pay_active_planned_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrecord",
            name="dingtalk_instance_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="钉钉审批实例ID",
            ),
        ),
    ]
