# Generated by Django 4.2.16 on 2026-07-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0035_approvalrecord_dingtalk_instance_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DingtalkInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="钉钉实例ID"
                    ),
                ),
                (
                    "process_code",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="模板code"
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="模板名"
                    ),
                ),
                (
                    "business_id",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="审批编号"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="标题"
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="摘要"
                    ),
                ),
                (
                    "applicant",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="申请人"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="部门"
                    ),
                ),
                (
                    "originator_userid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="发起人userid",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=16, verbose_name="金额"
                    ),
                ),
                (
                    "payee",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="收款方"
                    ),
                ),
                (
                    "ding_status",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=20,
                        verbose_name="钉钉状态",
                    ),
                ),
                (
                    "ding_result",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="钉钉结果"
                    ),
                ),
                (
                    "sys_status",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="系统状态"
                    ),
                ),
                (
                    "create_time",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="发起时间"
                    ),
                ),
                (
                    "approver_userids",
                    models.JSONField(
                        blank=True, default=list, verbose_name="审批人userid"
                    ),
                ),
                (
                    "raw",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="完整详情(归一)"
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="抓取时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="首次入库"),
                ),
            ],
            options={
                "db_table": "pk_dingtalk_instances",
                "indexes": [
                    models.Index(
                        fields=["process_code", "ding_status"],
                        name="pk_dingtalk_process_86e15d_idx",
                    )
                ],
            },
        ),
    ]
