# Generated by Django 4.2.16 on 2026-08-19 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0036_dingtalkinstance"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrecord",
            name="schedule_closed",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="排款结案"
            ),
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="schedule_closed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="结案时间"),
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="schedule_closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_approval_schedules",
                to="paikuan.paikuanuser",
            ),
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="schedule_closed_reason",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="结案原因"
            ),
        ),
    ]
