# Generated by Django 4.2.16 on 2026-08-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0037_approvalrecord_schedule_closed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalrecord",
            name="schedule_closed",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="排款已关闭"
            ),
        ),
        migrations.AlterField(
            model_name="approvalrecord",
            name="schedule_closed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="关闭时间"),
        ),
        migrations.AlterField(
            model_name="approvalrecord",
            name="schedule_closed_reason",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="关闭原因"
            ),
        ),
    ]
