# Generated by Django 4.2.16 on 2026-05-25 14:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("paikuan", "0003_jobpermission_alter_paikuanuser_job_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ARProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_no",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="项目编号",
                    ),
                ),
                (
                    "contract_name",
                    models.CharField(max_length=200, verbose_name="合同名称"),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="项目简称"
                    ),
                ),
                (
                    "delivery_dept",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="交付部门"
                    ),
                ),
                (
                    "sub_dept",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="二级部门"
                    ),
                ),
                (
                    "business_mode",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="业务模式"
                    ),
                ),
                (
                    "customer_level",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="客户等级"
                    ),
                ),
                (
                    "sales_contact",
                    models.CharField(max_length=100, verbose_name="销售对接人"),
                ),
                (
                    "project_manager",
                    models.CharField(max_length=100, verbose_name="项目负责人"),
                ),
                (
                    "is_shared",
                    models.BooleanField(default=False, verbose_name="共享业务"),
                ),
                (
                    "has_contract",
                    models.CharField(
                        choices=[("有", "有"), ("无", "无")],
                        default="无",
                        max_length=2,
                        verbose_name="有无合同",
                    ),
                ),
                (
                    "contract_date",
                    models.DateField(blank=True, null=True, verbose_name="签订日期"),
                ),
                (
                    "reconciliation_days",
                    models.IntegerField(default=0, verbose_name="合同对账期(天)"),
                ),
                (
                    "invoice_wait_days",
                    models.IntegerField(default=0, verbose_name="开票等待期(天)"),
                ),
                (
                    "settlement_wait_days",
                    models.IntegerField(default=0, verbose_name="结算等待期(天)"),
                ),
                (
                    "total_days",
                    models.IntegerField(default=0, verbose_name="总账期(天)"),
                ),
                (
                    "invoice_mode",
                    models.CharField(
                        choices=[("全额", "全额"), ("差额", "差额")],
                        default="全额",
                        max_length=4,
                        verbose_name="开票模式",
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        blank=True,
                        choices=[("专票", "专票"), ("普票", "普票")],
                        default="",
                        max_length=4,
                        verbose_name="专票/普票",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="税率",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_projects",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "ar_projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ARRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_dept",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=50,
                        verbose_name="交付部门",
                    ),
                ),
                (
                    "operation_year",
                    models.IntegerField(db_index=True, verbose_name="运作年"),
                ),
                (
                    "operation_month",
                    models.IntegerField(db_index=True, verbose_name="运作月"),
                ),
                (
                    "estimated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="预估上账金额",
                    ),
                ),
                (
                    "actual_invoice_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="实际开票金额",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="税额",
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="开票日期"
                    ),
                ),
                (
                    "account_diff_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="账实差额调整",
                    ),
                ),
                (
                    "outstanding_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="未回款金额",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="应收日期"
                    ),
                ),
                (
                    "reconciliation_time",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="对账时间"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ar_records",
                        to="paikuan.paikuanuser",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ar_records",
                        to="ar.arproject",
                    ),
                ),
            ],
            options={
                "db_table": "ar_records",
                "ordering": ["-operation_year", "-operation_month"],
            },
        ),
        migrations.CreateModel(
            name="ARPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_no", models.IntegerField(verbose_name="回款序号")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="回款金额"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(db_index=True, verbose_name="回款日期"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ar_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="ar.arrecord",
                    ),
                ),
            ],
            options={
                "db_table": "ar_payments",
                "ordering": ["ar_record", "payment_no"],
            },
        ),
        migrations.CreateModel(
            name="PaymentBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=20,
                        verbose_name="项目编号",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(max_length=200, verbose_name="项目简称/摘要"),
                ),
                (
                    "expected_date",
                    models.DateField(db_index=True, verbose_name="预计本月付款时间"),
                ),
                (
                    "sub_dept",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="二级部门"
                    ),
                ),
                (
                    "delivery_dept",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=50,
                        verbose_name="交付部门",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="金额"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_budgets",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "ar_payment_budgets",
                "ordering": ["expected_date"],
                "indexes": [
                    models.Index(
                        fields=["delivery_dept", "expected_date"],
                        name="ar_payment__deliver_8e1cc0_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CollectionBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=20,
                        verbose_name="项目编号",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(max_length=200, verbose_name="项目简称"),
                ),
                (
                    "expected_date",
                    models.DateField(db_index=True, verbose_name="预计本月收款时间"),
                ),
                (
                    "sub_dept",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="二级部门"
                    ),
                ),
                (
                    "delivery_dept",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=50,
                        verbose_name="交付部门",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="金额"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_budgets",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "ar_collection_budgets",
                "ordering": ["expected_date"],
                "indexes": [
                    models.Index(
                        fields=["delivery_dept", "expected_date"],
                        name="ar_collecti_deliver_e76425_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="arrecord",
            index=models.Index(
                fields=["delivery_dept", "due_date"],
                name="ar_records_deliver_0fa80e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="arrecord",
            index=models.Index(
                fields=["delivery_dept", "operation_year", "operation_month"],
                name="ar_records_deliver_9920bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="arrecord",
            index=models.Index(
                fields=["due_date"], name="ar_records_due_dat_ccb69f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arrecord",
            index=models.Index(
                fields=["outstanding_amount"], name="ar_records_outstan_faf226_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arrecord",
            index=models.Index(
                fields=["invoice_date"], name="ar_records_invoice_40d023_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arrecord",
            index=models.Index(
                fields=["reconciliation_time"], name="ar_records_reconci_441a3e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="arrecord",
            unique_together={("project", "operation_year", "operation_month")},
        ),
        migrations.AddIndex(
            model_name="arproject",
            index=models.Index(
                fields=["delivery_dept"], name="ar_projects_deliver_42ae9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arproject",
            index=models.Index(
                fields=["project_manager"], name="ar_projects_project_47445b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arproject",
            index=models.Index(
                fields=["sales_contact"], name="ar_projects_sales_c_1fe3ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arproject",
            index=models.Index(
                fields=["is_shared"], name="ar_projects_is_shar_d697c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arpayment",
            index=models.Index(
                fields=["ar_record", "payment_date"],
                name="ar_payments_ar_reco_ef45a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="arpayment",
            index=models.Index(
                fields=["payment_date"], name="ar_payments_payment_fd232e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="arpayment",
            unique_together={("ar_record", "payment_no")},
        ),
    ]
