# Generated by Django 4.2.16 on 2026-05-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ARProjectNoSeq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_dept",
                    models.CharField(max_length=50, verbose_name="交付部门"),
                ),
                ("biz_date", models.DateField(verbose_name="业务日期")),
                ("seq", models.IntegerField(default=0, verbose_name="序号")),
            ],
            options={
                "db_table": "ar_project_no_seq",
                "indexes": [
                    models.Index(
                        fields=["delivery_dept", "biz_date"],
                        name="ar_project__deliver_d0a8f7_idx",
                    )
                ],
                "unique_together": {("delivery_dept", "biz_date")},
            },
        ),
        migrations.CreateModel(
            name="ARImportRowDedup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("import_type", models.CharField(max_length=50)),
                ("batch_no", models.CharField(max_length=128)),
                ("row_key", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ar_import_row_dedup",
                "unique_together": {("import_type", "batch_no", "row_key")},
            },
        ),
        migrations.CreateModel(
            name="APIIdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(db_index=True)),
                ("api_name", models.CharField(max_length=100)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("response_snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "api_idempotency_records",
                "unique_together": {("user_id", "api_name", "idempotency_key")},
            },
        ),
    ]
