# Generated by Django 4.2.16 on 2026-05-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arproject",
            name="invoice_type",
            field=models.CharField(
                blank=True,
                choices=[("专票", "专票"), ("普票", "普票"), ("不开票", "不开票")],
                default="",
                max_length=4,
                verbose_name="专票/普票/不开票",
            ),
        ),
    ]
