# Generated by Django 4.2.16 on 2026-05-28 12:05

from django.db import migrations, models


def copy_time_to_date(apps, schema_editor):
    """Preserve existing reconciliation data: copy date portion before dropping the column."""
    ARRecord = apps.get_model("ar", "ARRecord")
    for rec in ARRecord.objects.exclude(reconciliation_time__isnull=True).only(
        "id", "reconciliation_time"
    ):
        ARRecord.objects.filter(pk=rec.pk).update(
            reconciliation_date=rec.reconciliation_time.date()
        )


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0002_update_invoice_type_choices"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="arrecord",
            name="ar_records_reconci_441a3e_idx",
        ),
        migrations.AlterUniqueTogether(
            name="arrecord",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="arrecord",
            name="reconciliation_date",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="对账日期"
            ),
        ),
        migrations.RunPython(copy_time_to_date, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="arrecord",
            index=models.Index(
                fields=["reconciliation_date"], name="ar_records_reconci_690ef3_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="arrecord",
            name="reconciliation_time",
        ),
    ]
