# Generated by Django 4.2.16 on 2026-05-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0003_remove_arrecord_ar_records_reconci_441a3e_idx_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="arrecord",
            constraint=models.CheckConstraint(
                check=models.Q(("outstanding_amount__gte", 0)),
                name="ar_record_outstanding_non_negative",
            ),
        ),
    ]
