# Generated by Django 4.2.16 on 2026-05-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0005_rename_settlement_wait_days_to_post_invoice_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arproject",
            name="post_invoice_days",
            field=models.IntegerField(default=0, verbose_name="票后等待期(天)"),
        ),
    ]
