# Generated by Django 4.2.16 on 2026-06-02 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0009_alter_payment_plan_adjustment"),
        ("ar", "0006_alter_arproject_post_invoice_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_dept",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=50,
                        verbose_name="交付部门",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("预收", "预收"), ("预付", "预付")],
                        db_index=True,
                        max_length=4,
                        verbose_name="方向",
                    ),
                ),
                (
                    "counterparty",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="往来单位"
                    ),
                ),
                (
                    "occur_year",
                    models.IntegerField(db_index=True, verbose_name="发生年"),
                ),
                (
                    "occur_month",
                    models.IntegerField(db_index=True, verbose_name="发生月"),
                ),
                (
                    "occur_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="款项日期"
                    ),
                ),
                (
                    "advance_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="预收/预付金额",
                    ),
                ),
                (
                    "expected_writeoff_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="预计核销日期",
                    ),
                ),
                (
                    "written_off_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="已核销金额",
                    ),
                ),
                (
                    "balance_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="未核销余额",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_advance_records",
                        to="paikuan.paikuanuser",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advance_records",
                        to="ar.arproject",
                    ),
                ),
            ],
            options={
                "db_table": "ar_advance_records",
                "ordering": ["-occur_year", "-occur_month", "-occur_date"],
            },
        ),
        migrations.CreateModel(
            name="AdvanceWriteoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("writeoff_no", models.IntegerField(verbose_name="核销序号")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="核销金额"
                    ),
                ),
                (
                    "writeoff_date",
                    models.DateField(db_index=True, verbose_name="核销日期"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "advance_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writeoffs",
                        to="ar.advancerecord",
                    ),
                ),
            ],
            options={
                "db_table": "ar_advance_writeoffs",
                "ordering": ["advance_record", "writeoff_no"],
                "indexes": [
                    models.Index(
                        fields=["advance_record", "writeoff_date"],
                        name="ar_advance__advance_72ba2b_idx",
                    ),
                    models.Index(
                        fields=["writeoff_date"], name="ar_advance__writeof_c00632_idx"
                    ),
                ],
                "unique_together": {("advance_record", "writeoff_no")},
            },
        ),
        migrations.AddIndex(
            model_name="advancerecord",
            index=models.Index(
                fields=["direction", "delivery_dept"],
                name="ar_advance__directi_d4f541_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="advancerecord",
            index=models.Index(
                fields=["delivery_dept", "occur_year", "occur_month"],
                name="ar_advance__deliver_ee6c44_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="advancerecord",
            index=models.Index(
                fields=["occur_date"], name="ar_advance__occur_d_35e290_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="advancerecord",
            index=models.Index(
                fields=["balance_amount"], name="ar_advance__balance_55003c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="advancerecord",
            constraint=models.CheckConstraint(
                check=models.Q(("balance_amount__gte", 0)),
                name="advance_balance_non_negative",
            ),
        ),
    ]
