# Generated by Django 4.2.16 on 2026-06-02 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0007_advancerecord_advancewriteoff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advancewriteoff",
            name="ar_payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advance_writeoff",
                to="ar.arpayment",
            ),
        ),
        migrations.AddField(
            model_name="advancewriteoff",
            name="ar_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advance_offsets",
                to="ar.arrecord",
            ),
        ),
        migrations.AddField(
            model_name="arpayment",
            name="source",
            field=models.CharField(
                choices=[("回款", "回款"), ("预收抵扣", "预收抵扣")],
                db_index=True,
                default="回款",
                max_length=8,
                verbose_name="回款来源",
            ),
        ),
    ]
