# Generated by Django 4.2.16 on 2026-06-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0008_advancewriteoff_ar_payment_advancewriteoff_ar_record_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arproject",
            name="customer_name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="客户名称"
            ),
        ),
    ]
