# Generated by Django 4.2.16 on 2026-06-02 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0010_payment_project_no"),
        ("ar", "0009_arproject_customer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="advancewriteoff",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prepaid_offsets",
                to="paikuan.payment",
            ),
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="供应商名称"
                    ),
                ),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[("private", "私有"), ("public", "公共")],
                        db_index=True,
                        default="public",
                        max_length=8,
                        verbose_name="类型",
                    ),
                ),
                (
                    "delivery_dept",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=50,
                        verbose_name="交付部门",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="联系人"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_suppliers",
                        to="paikuan.paikuanuser",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suppliers",
                        to="ar.arproject",
                    ),
                ),
            ],
            options={
                "db_table": "ar_suppliers",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["supplier_type", "delivery_dept"],
                        name="ar_supplier_supplie_95859e_idx",
                    )
                ],
            },
        ),
    ]
