# Generated by Django 4.2.16 on 2026-06-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0010_advancewriteoff_payment_supplier"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="arrecord",
            index=models.Index(
                fields=["operation_year", "operation_month"],
                name="ar_records_operati_6fdc4c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="arrecord",
            index=models.Index(
                fields=["estimated_amount"], name="ar_records_estimat_351602_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arrecord",
            index=models.Index(
                fields=["actual_invoice_amount"], name="ar_records_actual__ed2e0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arrecord",
            index=models.Index(
                fields=["created_at"], name="ar_records_created_50e29b_idx"
            ),
        ),
    ]
