# Generated by Django 4.2.16 on 2026-06-06 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0014_alter_paymentinstallment_id"),
        ("ar", "0014_customer_arproject_draft"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=50,
                        verbose_name="合同编号",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="合同名称"
                    ),
                ),
                (
                    "delivery_dept",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=50,
                        verbose_name="交付部门",
                    ),
                ),
                (
                    "sign_date",
                    models.DateField(blank=True, null=True, verbose_name="签订日期"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="合同金额",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contracts",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "ar_contracts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContractProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True,
                        help_text="项目挂多个合同时，标记其主合同",
                        verbose_name="主合同",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_links",
                        to="ar.contract",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_links",
                        to="ar.arproject",
                    ),
                ),
            ],
            options={
                "db_table": "ar_contract_projects",
                "ordering": ["contract", "id"],
                "unique_together": {("contract", "project")},
            },
        ),
        migrations.CreateModel(
            name="ContractParty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("main", "主客户"), ("sub", "次客户")],
                        default="main",
                        max_length=8,
                        verbose_name="角色",
                    ),
                ),
                (
                    "share",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="分成比例(%)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties",
                        to="ar.contract",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_links",
                        to="ar.customer",
                    ),
                ),
            ],
            options={
                "db_table": "ar_contract_parties",
                "ordering": ["contract", "id"],
                "unique_together": {("contract", "customer")},
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="customers",
            field=models.ManyToManyField(
                related_name="contracts", through="ar.ContractParty", to="ar.customer"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="projects",
            field=models.ManyToManyField(
                related_name="contracts",
                through="ar.ContractProject",
                to="ar.arproject",
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["name", "delivery_dept"], name="ar_contract_name_fd6245_idx"
            ),
        ),
    ]
