# Generated by Django 4.2.16 on 2026-06-07 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0014_alter_paymentinstallment_id"),
        ("ar", "0016_backfill_contracts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="标题")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "bu",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=50,
                        verbose_name="事业部",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="类型"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "高"), ("medium", "中"), ("low", "低")],
                        default="medium",
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "待处理"),
                            ("in_progress", "处理中"),
                            ("done", "已完成"),
                            ("dismissed", "已忽略"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "assignee",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="负责人"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="截止日期"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "source_signal",
                    models.JSONField(blank=True, default=dict, verbose_name="来源信号"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_action_items",
                        to="paikuan.paikuanuser",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_action_items",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "ar_action_items",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "bu"], name="ar_action_i_status_fc33cd_idx"
                    )
                ],
            },
        ),
    ]
