# Generated by Django 4.2.16 on 2026-06-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0019_backfill_customers_from_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_date",
            field=models.DateField(
                blank=True,
                help_text="可手工指定的客户日期（如 2026-01-01），区别于系统记录的创建时间",
                null=True,
                verbose_name="建档日期",
            ),
        ),
    ]
