# Generated by Django 4.2.16 on 2026-06-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0022_customer_dept_isolation"),
    ]

    operations = [
        migrations.AddField(
            model_name="arproject",
            name="status",
            field=models.CharField(
                choices=[("运作中", "运作中"), ("中断", "中断"), ("结束", "结束")],
                db_index=True,
                default="运作中",
                max_length=10,
                verbose_name="状态",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[("运作中", "运作中"), ("中断", "中断"), ("结束", "结束")],
                db_index=True,
                default="运作中",
                max_length=10,
                verbose_name="状态",
            ),
        ),
    ]
