# Generated by Django 4.2.16 on 2026-06-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0015_auditlog"),
        ("ar", "0023_project_customer_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashPoolTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_dept",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="调出事业部"
                    ),
                ),
                (
                    "to_dept",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="调入事业部"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="调拨金额"
                    ),
                ),
                (
                    "transfer_date",
                    models.DateField(db_index=True, verbose_name="调拨日期"),
                ),
                (
                    "expected_return_date",
                    models.DateField(blank=True, null=True, verbose_name="约定归还日"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pool_transfers",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "ar_cash_pool_transfers",
                "ordering": ["-transfer_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CashPoolConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_dept",
                    models.CharField(max_length=50, unique=True, verbose_name="事业部"),
                ),
                (
                    "initial_date",
                    models.DateField(
                        help_text="该日终的账面资金为期初值；之后的流水才计入水位",
                        verbose_name="期初基准日",
                    ),
                ),
                (
                    "initial_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="期初金额",
                    ),
                ),
                (
                    "warning_days",
                    models.IntegerField(
                        default=30,
                        help_text="警戒线 = 未来N天刚性流出（已审批待付）",
                        verbose_name="警戒窗口(天)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_pool_configs",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "ar_cash_pool_configs",
                "ordering": ["delivery_dept"],
            },
        ),
    ]
