# Generated by Django 4.2.16 on 2026-06-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0016_paikuanuser_pwd_changed_at"),
        ("ar", "0024_cashpooltransfer_cashpoolconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashpoolconfig",
            name="warning_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="手动设定的最低安全余额；设置后优先于按天数推算",
                max_digits=15,
                null=True,
                verbose_name="资金预警线(元)",
            ),
        ),
        migrations.AddField(
            model_name="cashpooltransfer",
            name="review_notes",
            field=models.TextField(blank=True, default="", verbose_name="审批意见"),
        ),
        migrations.AddField(
            model_name="cashpooltransfer",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审批时间"),
        ),
        migrations.AddField(
            model_name="cashpooltransfer",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_pool_transfers",
                to="paikuan.paikuanuser",
            ),
        ),
        migrations.AddField(
            model_name="cashpooltransfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审批"),
                    ("approved", "已生效"),
                    ("rejected", "已拒绝"),
                ],
                db_index=True,
                default="approved",
                max_length=10,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="cashpoolconfig",
            name="initial_date",
            field=models.DateField(
                help_text="该日终的账面资金为期初值；之后的收支流水才计入余额",
                verbose_name="期初基准日",
            ),
        ),
        migrations.AlterField(
            model_name="cashpoolconfig",
            name="warning_days",
            field=models.IntegerField(
                default=30,
                help_text="未设固定预警线时：资金预警线 = 未来N天刚性流出（已审批待付）",
                verbose_name="预警窗口(天)",
            ),
        ),
    ]
