# Generated by Django 4.2.16 on 2026-06-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0025_cashpoolconfig_warning_amount_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="advancewriteoff",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("payment__isnull", False),
                    ("ar_payment__isnull", False),
                    _negated=True,
                ),
                name="writeoff_payment_xor_ar_payment",
            ),
        ),
    ]
