# Generated by Django 4.2.16 on 2026-06-11 04:24
import datetime

from django.db import migrations, models


def backfill_operation_date(apps, schema_editor):
    """历史年/月数据 → 当月1日（如 2026年5月 → 2026-05-01）。"""
    ARRecord = apps.get_model('ar', 'ARRecord')
    batch = []
    for rec in ARRecord.objects.filter(operation_date__isnull=True).only(
            'id', 'operation_year', 'operation_month').iterator():
        try:
            rec.operation_date = datetime.date(rec.operation_year, rec.operation_month, 1)
        except (ValueError, TypeError):
            continue   # 异常年月留空，由人工修复（不阻断迁移）
        batch.append(rec)
        if len(batch) >= 500:
            ARRecord.objects.bulk_update(batch, ['operation_date'])
            batch = []
    if batch:
        ARRecord.objects.bulk_update(batch, ['operation_date'])


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0026_advancewriteoff_writeoff_payment_xor_ar_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arrecord",
            options={"ordering": ["-operation_date"]},
        ),
        migrations.AddField(
            model_name="arrecord",
            name="operation_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="应收发生日期；历史年/月数据迁移为当月1日",
                null=True,
                verbose_name="运作日期",
            ),
        ),
        migrations.RunPython(backfill_operation_date, migrations.RunPython.noop),
    ]
