# Generated by Django 4.2.16 on 2026-06-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0027_alter_arrecord_options_arrecord_operation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="arrecord",
            name="target_collection_date",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="目标回款日期"
            ),
        ),
    ]
