# Generated by Django 4.2.16 on 2026-06-11 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0018_approvalrecord_project_short_name_and_more"),
        ("ar", "0028_arrecord_target_collection_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="arproject",
            name="cycle_start_day",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="对账周期起始日"
            ),
        ),
        migrations.CreateModel(
            name="ARAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="调整金额"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="调整原因"
                    ),
                ),
                (
                    "adjust_date",
                    models.DateField(blank=True, null=True, verbose_name="调整日期"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ar_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="ar.arrecord",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ar_adjustments",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "ar_adjustments",
                "ordering": ["ar_record", "id"],
            },
        ),
    ]
