# Generated by Django 4.2.16 on 2026-06-11 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0030_backfill_adjustments"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvanceInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("install_no", models.IntegerField(verbose_name="收付序号")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="收付金额"
                    ),
                ),
                (
                    "occur_date",
                    models.DateField(db_index=True, verbose_name="收付日期"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "advance_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="ar.advancerecord",
                    ),
                ),
            ],
            options={
                "db_table": "ar_advance_installments",
                "ordering": ["advance_record", "install_no"],
                "indexes": [
                    models.Index(
                        fields=["advance_record", "occur_date"],
                        name="ar_advance__advance_2d742b_idx",
                    ),
                    models.Index(
                        fields=["occur_date"], name="ar_advance__occur_d_17f375_idx"
                    ),
                ],
                "unique_together": {("advance_record", "install_no")},
            },
        ),
    ]
