# Generated by Django 4.2.16 on 2026-06-12 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0020_backfill_scheduled_amount"),
        ("ar", "0032_backfill_advance_installments"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchInvoiceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_no",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="批次号"
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(db_index=True, verbose_name="开票日期"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="开票金额(价税合计)",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="税额(差额模式手填)",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="备注"
                    ),
                ),
                (
                    "allocations",
                    models.JSONField(default=list, verbose_name="分摊明细"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_batch_invoices",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "ar_batch_invoice_events",
                "ordering": ["batch_no", "invoice_date", "id"],
                "indexes": [
                    models.Index(
                        fields=["batch_no", "invoice_date"],
                        name="ar_batch_in_batch_n_35fd67_idx",
                    )
                ],
            },
        ),
    ]
