# Generated by Django 4.2.16 on 2026-06-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0033_batchinvoiceevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="arpayment",
            name="counterparty_dept",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=50,
                verbose_name="往来部门",
            ),
        ),
        migrations.AlterField(
            model_name="arpayment",
            name="source",
            field=models.CharField(
                choices=[
                    ("回款", "回款"),
                    ("预收抵扣", "预收抵扣"),
                    ("内部往来", "内部往来"),
                ],
                db_index=True,
                default="回款",
                max_length=8,
                verbose_name="回款来源",
            ),
        ),
    ]
