# Generated by Django 4.2.16 on 2026-06-23 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0025_add_must_change_password"),
        ("ar", "0036_reconcile_adjustment_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="ARFilterScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="方案名称")),
                (
                    "module",
                    models.CharField(
                        db_index=True,
                        default="ar_records",
                        max_length=40,
                        verbose_name="所属列表",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("private", "私有"), ("public", "公共")],
                        db_index=True,
                        default="private",
                        max_length=10,
                        verbose_name="可见范围",
                    ),
                ),
                (
                    "conditions",
                    models.TextField(
                        blank=True, default="[]", verbose_name="条件快照(JSON)"
                    ),
                ),
                (
                    "match",
                    models.CharField(
                        default="all", max_length=4, verbose_name="组间连接"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ar_filter_schemes",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "ar_filter_schemes",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["module", "scope"], name="ar_filter_s_module_4acb6d_idx"
                    ),
                    models.Index(
                        fields=["owner", "module"],
                        name="ar_filter_s_owner_i_65d057_idx",
                    ),
                ],
            },
        ),
    ]
