# Generated by Django 4.2.16 on 2026-06-23 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0025_add_must_change_password"),
        ("ar", "0037_arfilterscheme"),
    ]

    operations = [
        migrations.CreateModel(
            name="ARSchemeDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        db_index=True,
                        default="ar_records",
                        max_length=40,
                        verbose_name="所属列表",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_of",
                        to="ar.arfilterscheme",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ar_scheme_defaults",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "ar_scheme_defaults",
                "unique_together": {("user", "module")},
            },
        ),
    ]
