# Generated by Django 4.2.16 on 2026-06-23 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0026_listscheme_listschemedefault_and_more"),
        ("ar", "0038_arschemedefault"),
    ]

    operations = [
        migrations.CreateModel(
            name="ARCollectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("call", "电话"),
                            ("email", "邮件"),
                            ("visit", "拜访"),
                            ("meeting", "会议"),
                            ("other", "其他"),
                        ],
                        default="call",
                        max_length=10,
                        verbose_name="跟进类型",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="联系人"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="跟进内容"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待回复"),
                            ("in_progress", "跟进中"),
                            ("resolved", "已解决"),
                            ("no_response", "无响应"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="计划跟进日期"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ar_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_logs",
                        to="ar.arrecord",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_logs",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "ar_collection_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ar_record", "created_at"],
                        name="ar_collecti_ar_reco_00c5f0_idx",
                    )
                ],
            },
        ),
    ]
