# Generated by Django 4.2.16 on 2026-06-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0039_arcollectionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="arrecord",
            name="collector",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=100,
                verbose_name="催收负责人",
            ),
        ),
    ]
