# Generated by Django 4.2.16 on 2026-06-23 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0026_listscheme_listschemedefault_and_more"),
        ("ar", "0040_arrecord_collector"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgingBucketConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bucket1",
                    models.PositiveIntegerField(default=30, verbose_name="桶1上限(天)"),
                ),
                (
                    "bucket2",
                    models.PositiveIntegerField(default=60, verbose_name="桶2上限(天)"),
                ),
                (
                    "bucket3",
                    models.PositiveIntegerField(default=90, verbose_name="桶3上限(天)"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aging_config_updates",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "ar_aging_bucket_config",
            },
        ),
    ]
