# Generated by Django 4.2.16 on 2026-06-24 10:47

import ar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0042_aractivity_arattachment_counters"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aractivity",
            new_name="ar_activiti_ar_reco_e2be15_idx",
            old_name="ar_activiti_ar_reco_idx",
        ),
        migrations.RenameIndex(
            model_name="arattachment",
            new_name="ar_attachme_ar_reco_5c605a_idx",
            old_name="ar_attachme_ar_reco_idx",
        ),
        migrations.AlterField(
            model_name="aractivity",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="arattachment",
            name="file",
            field=models.FileField(
                max_length=500,
                upload_to=ar.models._attachment_upload_path,
                verbose_name="文件",
            ),
        ),
        migrations.AlterField(
            model_name="arattachment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
