# Generated by Django 4.2.16 on 2026-07-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0043_fix_index_names_file_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="arpayment",
            name="account",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="收款账户"
            ),
        ),
        migrations.AddField(
            model_name="arpayment",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("现金", "现金"),
                    ("微信", "微信"),
                    ("银行转账", "银行转账"),
                    ("承兑汇票", "承兑汇票"),
                ],
                db_index=True,
                default="",
                max_length=12,
                verbose_name="回款方式",
            ),
        ),
    ]
