# Generated by Django 4.2.16 on 2026-07-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0045_backfill_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="arpayment",
            name="draft_status",
            field=models.CharField(
                blank=True,
                choices=[("未承兑", "未承兑"), ("已承兑", "已承兑")],
                db_index=True,
                default="",
                max_length=6,
                verbose_name="承兑状态",
            ),
        ),
    ]
