# Generated by Django 4.2.16 on 2026-07-08 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0036_dingtalkinstance"),
        ("ar", "0047_backfill_draft_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_date",
                    models.DateField(db_index=True, verbose_name="收款日期"),
                ),
                (
                    "delivery_dept",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="事业部"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="收款金额"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        db_index=True, max_length=40, verbose_name="收款来源"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="收款方式"
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="收款账户"
                    ),
                ),
                (
                    "payer",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="付款方"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="摘要/备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_receipts",
                        to="paikuan.paikuanuser",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_receipts",
                        to="ar.arproject",
                    ),
                ),
            ],
            options={
                "db_table": "ar_daily_receipts",
                "ordering": ["-receipt_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["delivery_dept", "receipt_date"],
                        name="ar_daily_re_deliver_4d88d6_idx",
                    )
                ],
            },
        ),
    ]
