# Generated by Django 4.2.16 on 2026-07-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0048_dailyreceipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="advancerecord",
            name="refunded_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="已退款金额"
            ),
        ),
        migrations.AddField(
            model_name="dailyreceipt",
            name="advance_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds",
                to="ar.advancerecord",
            ),
        ),
    ]
