# Generated by Django 4.2.16 on 2026-07-10 00:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0036_dingtalkinstance"),
        ("ar", "0049_advancerecord_refunded_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arrecord",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "ordering": ["-operation_date"],
            },
        ),
        migrations.AlterModelManagers(
            name="arrecord",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="arrecord",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="删除时间"
            ),
        ),
        migrations.AddField(
            model_name="arrecord",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_ar_records",
                to="paikuan.paikuanuser",
            ),
        ),
    ]
