# Generated by Django 4.2.16 on 2026-08-15 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0036_dingtalkinstance"),
        ("ar", "0051_arfilterscheme_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="ARInvoiceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_no", models.IntegerField(verbose_name="开票序号")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="开票金额(价税合计)",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="税额(差额模式手填)",
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="开票日期"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="备注"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ar_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_entries",
                        to="ar.arrecord",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ar_invoices",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "ar_invoice_entries",
                "ordering": ["ar_record", "entry_no", "id"],
                "indexes": [
                    models.Index(
                        fields=["ar_record", "invoice_date"],
                        name="ar_invoice__ar_reco_7397f7_idx",
                    )
                ],
            },
        ),
    ]
