# Generated by Django 4.2.16 on 2026-08-18 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0036_dingtalkinstance"),
        ("ar", "0053_backfill_invoice_entries"),
    ]

    operations = [
        migrations.AddField(
            model_name="advancerecord",
            name="aging_base_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="账龄承袭基准日"
            ),
        ),
        migrations.AddField(
            model_name="advancerecord",
            name="transferred_in_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="累计转入"
            ),
        ),
        migrations.AddField(
            model_name="advancerecord",
            name="transferred_out_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="累计转出"
            ),
        ),
        migrations.CreateModel(
            name="AdvanceTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="转移金额"
                    ),
                ),
                (
                    "transfer_date",
                    models.DateField(db_index=True, verbose_name="转移日期"),
                ),
                ("reason", models.CharField(max_length=200, verbose_name="转移原因")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_advance_transfers",
                        to="paikuan.paikuanuser",
                    ),
                ),
                (
                    "from_advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="ar.advancerecord",
                    ),
                ),
                (
                    "to_advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="ar.advancerecord",
                    ),
                ),
            ],
            options={
                "db_table": "ar_advance_transfers",
                "ordering": ["transfer_date", "id"],
                "indexes": [
                    models.Index(
                        fields=["transfer_date"], name="ar_advance__transfe_85c2d3_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="advancetransfer",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)),
                name="advance_transfer_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="advancetransfer",
            constraint=models.CheckConstraint(
                check=models.Q(("from_advance", models.F("to_advance")), _negated=True),
                name="advance_transfer_not_self",
            ),
        ),
    ]
