# Generated by Django 4.2.16 on 2026-08-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0054_advancerecord_aging_base_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advancetransfer",
            name="detail",
            field=models.JSONField(blank=True, default=dict, verbose_name="迁移载荷"),
        ),
        migrations.AddField(
            model_name="advancetransfer",
            name="kind",
            field=models.CharField(
                choices=[("equity", "权益划转"), ("cash_lines", "整笔迁移")],
                db_index=True,
                default="equity",
                max_length=12,
                verbose_name="转移类型",
            ),
        ),
    ]
