# Generated by Django 4.2.16 on 2026-05-24 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaiwuUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=15, unique=True, verbose_name="手机号"
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(max_length=256, verbose_name="密码哈希"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "role",
                    models.CharField(
                        default="viewer", max_length=20, verbose_name="角色"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="职务"
                    ),
                ),
                (
                    "departments",
                    models.JSONField(default=list, verbose_name="负责事业部"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="是否已审批"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_users",
                        to="caiwu.caiwuuser",
                    ),
                ),
            ],
            options={
                "db_table": "caiwu_user",
            },
        ),
        migrations.CreateModel(
            name="L1Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="科目名称"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_profit_driver",
                    models.BooleanField(
                        default=False, verbose_name="利润驱动因素（瀑布图用）"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "caiwu_l1category",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="L3Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_unit",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="事业部"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="科目明细")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "l1_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="l3_categories",
                        to="caiwu.l1category",
                    ),
                ),
            ],
            options={
                "db_table": "caiwu_l3category",
                "ordering": ["sort_order", "id"],
                "unique_together": {("business_unit", "l1_category", "name")},
            },
        ),
        migrations.CreateModel(
            name="L2Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_unit",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="事业部"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="项目部名称")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "db_table": "caiwu_l2category",
                "ordering": ["sort_order", "id"],
                "unique_together": {("business_unit", "name")},
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_unit",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="事业部"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年份")),
                ("month", models.IntegerField(verbose_name="月份")),
                (
                    "status",
                    models.CharField(
                        default="draft", max_length=20, verbose_name="状态"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                ("row_count", models.IntegerField(default=0, verbose_name="数据行数")),
                (
                    "file_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="原文件名"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches",
                        to="caiwu.caiwuuser",
                    ),
                ),
            ],
            options={
                "db_table": "caiwu_importbatch",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="金额"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="caiwu.importbatch",
                    ),
                ),
                (
                    "l1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="caiwu.l1category",
                    ),
                ),
                (
                    "l2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="caiwu.l2category",
                    ),
                ),
                (
                    "l3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="caiwu.l3category",
                    ),
                ),
            ],
            options={
                "db_table": "caiwu_financialentry",
            },
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["business_unit", "year", "month", "status"],
                name="caiwu_impor_busines_ae1b81_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["year", "month", "status"], name="caiwu_impor_year_8db641_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialentry",
            index=models.Index(
                fields=["batch", "l1"], name="caiwu_finan_batch_i_9c66dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialentry",
            index=models.Index(
                fields=["batch", "l1", "l2"], name="caiwu_finan_batch_i_c6b0d0_idx"
            ),
        ),
    ]
