# Generated by Django 4.2.16 on 2026-05-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0009_alter_payment_plan_adjustment"),
        ("caiwu", "0005_fix_l1_is_profit_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="caiwu_batches",
                to="paikuan.paikuanuser",
            ),
        ),
    ]
