# Generated by Django 4.2.16 on 2026-05-31 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0009_alter_payment_plan_adjustment"),
        ("caiwu", "0006_importbatch_uploaded_by_paikuanuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_unit",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="事业部"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年份")),
                (
                    "month",
                    models.IntegerField(
                        default=0,
                        help_text="0=年度目标，1-12=当月目标",
                        verbose_name="月份",
                    ),
                ),
                (
                    "target_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="目标收入",
                    ),
                ),
                (
                    "target_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="目标利润",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caiwu_targets",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "caiwu_financial_target",
                "ordering": ["business_unit", "year", "month"],
                "indexes": [
                    models.Index(
                        fields=["year", "month"], name="caiwu_finan_year_31195d_idx"
                    )
                ],
                "unique_together": {("business_unit", "year", "month")},
            },
        ),
    ]
