# Generated by Django 4.2.16 on 2026-06-05 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0014_alter_paymentinstallment_id"),
        ("caiwu", "0008_financialtarget_gross_profit"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMargin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_unit",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="事业部"
                    ),
                ),
                ("year", models.IntegerField(db_index=True, verbose_name="年")),
                ("month", models.IntegerField(db_index=True, verbose_name="月")),
                (
                    "project_name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="项目名称"
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=16, verbose_name="收入"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="主营成本",
                    ),
                ),
                (
                    "sales_exp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="销售费用",
                    ),
                ),
                (
                    "mgmt_exp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="管理费用",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_project_margins",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "caiwu_project_margin",
                "ordering": ["business_unit", "year", "month", "project_name"],
                "indexes": [
                    models.Index(
                        fields=["business_unit", "year", "month"],
                        name="caiwu_proje_busines_757824_idx",
                    )
                ],
            },
        ),
    ]
