# Generated by Django 4.2.16 on 2026-06-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0014_alter_paymentinstallment_id"),
        ("caiwu", "0009_projectmargin"),
    ]

    operations = [
        migrations.CreateModel(
            name="CockpitKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        db_index=True,
                        default="全集团",
                        max_length=50,
                        verbose_name="范围",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        default="insight", max_length=20, verbose_name="类型"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="标题"
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "source",
                    models.CharField(
                        default="user", max_length=10, verbose_name="来源"
                    ),
                ),
                ("pinned", models.BooleanField(default=False, verbose_name="置顶")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cockpit_knowledge",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "caiwu_cockpit_knowledge",
                "ordering": ["-pinned", "-created_at"],
                "indexes": [
                    models.Index(fields=["scope"], name="caiwu_cockp_scope_564ba7_idx")
                ],
            },
        ),
    ]
