# Generated by Django 4.2.16 on 2026-07-05 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("caiwu", "0010_cockpitknowledge"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_unit",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="记账主体"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年")),
                ("month", models.IntegerField(verbose_name="月")),
                (
                    "filename",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="文件名"
                    ),
                ),
                ("row_count", models.IntegerField(default=0, verbose_name="明细行数")),
                (
                    "uploaded_by",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="上传人"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
            ],
            options={
                "db_table": "caiwu_internal_batch",
            },
        ),
        migrations.CreateModel(
            name="InternalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_unit",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="记账主体"
                    ),
                ),
                (
                    "counterparty",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=32,
                        verbose_name="对方主体",
                    ),
                ),
                (
                    "counterparty_raw",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="对方原文"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年")),
                ("month", models.IntegerField(verbose_name="月")),
                (
                    "biz_date",
                    models.DateField(blank=True, null=True, verbose_name="日期"),
                ),
                (
                    "voucher_no",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="凭证字号"
                    ),
                ),
                (
                    "subject_code",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="科目编码"
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="科目名称"
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="摘要"
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18, verbose_name="借方"
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=18, verbose_name="贷方"
                    ),
                ),
                (
                    "side",
                    models.CharField(default="ar", max_length=4, verbose_name="方向"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="caiwu.internalbatch",
                    ),
                ),
            ],
            options={
                "db_table": "caiwu_internal_entry",
            },
        ),
        migrations.AddIndex(
            model_name="internalbatch",
            index=models.Index(
                fields=["year", "month"], name="caiwu_inter_year_45907d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internalentry",
            index=models.Index(
                fields=["business_unit", "counterparty", "year", "month"],
                name="caiwu_inter_busines_c232d3_idx",
            ),
        ),
    ]
