# Generated by Django 4.2.16 on 2026-07-05 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("caiwu", "0011_internalbatch_internalentry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalbatch",
            name="kind",
            field=models.CharField(
                default="detail", max_length=10, verbose_name="数据类型"
            ),
        ),
        migrations.CreateModel(
            name="InternalBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_unit",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="记账主体"
                    ),
                ),
                (
                    "counterparty",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=32,
                        verbose_name="对方主体",
                    ),
                ),
                (
                    "counterparty_raw",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="对方原文"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年")),
                ("month", models.IntegerField(verbose_name="月")),
                (
                    "subject_code",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="科目编码"
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="科目名称"
                    ),
                ),
                (
                    "opening",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="期初(借-贷)",
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="本期借方",
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="本期贷方",
                    ),
                ),
                (
                    "closing",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="期末(借-贷)",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="caiwu.internalbatch",
                    ),
                ),
            ],
            options={
                "db_table": "caiwu_internal_balance",
                "indexes": [
                    models.Index(
                        fields=["business_unit", "counterparty", "year", "month"],
                        name="caiwu_inter_busines_c0cd1c_idx",
                    )
                ],
            },
        ),
    ]
