# Generated by Django 4.2.16 on 2026-07-05 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0034_payment_pay_active_planned_idx"),
        ("caiwu", "0012_internalbatch_kind_internalbalance"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.SmallIntegerField(verbose_name="评价")),
                (
                    "question",
                    models.TextField(blank=True, default="", verbose_name="用户提问"),
                ),
                (
                    "answer",
                    models.TextField(blank=True, default="", verbose_name="AI 回答"),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="补充说明"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="分析范围"
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True, verbose_name="年")),
                (
                    "month",
                    models.IntegerField(blank=True, null=True, verbose_name="月"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_feedback",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "caiwu_ai_feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
