# Generated by Django 4.2.16 on 2026-07-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caiwu", "0013_aifeedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="日期")),
                (
                    "kind",
                    models.CharField(
                        default="other", max_length=20, verbose_name="用途"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="模型"
                    ),
                ),
                (
                    "prompt_tokens",
                    models.BigIntegerField(default=0, verbose_name="输入tokens"),
                ),
                (
                    "completion_tokens",
                    models.BigIntegerField(default=0, verbose_name="输出tokens"),
                ),
                ("calls", models.IntegerField(default=0, verbose_name="调用次数")),
            ],
            options={
                "db_table": "caiwu_ai_usage",
                "unique_together": {("date", "kind", "model")},
            },
        ),
    ]
