# Generated by Django 4.2.16 on 2026-07-07 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0034_payment_pay_active_planned_idx"),
        ("caiwu", "0014_aiusage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CockpitChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "messages",
                    models.JSONField(blank=True, default=list, verbose_name="对话消息"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cockpit_chat",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "caiwu_cockpit_chat",
            },
        ),
    ]
