# Generated by Django 4.2.16 on 2026-07-11 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paikuan", "0036_dingtalkinstance"),
        ("caiwu", "0015_cockpitchat"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloseChecklistNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="年")),
                ("month", models.PositiveIntegerField(verbose_name="月")),
                (
                    "item_key",
                    models.CharField(max_length=64, verbose_name="检查项 key"),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="负责人"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="处理说明"
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(default=False, verbose_name="本月已确认"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="close_checklist_notes",
                        to="paikuan.paikuanuser",
                    ),
                ),
            ],
            options={
                "db_table": "caiwu_close_checklist_note",
                "unique_together": {("year", "month", "item_key")},
            },
        ),
    ]
