from django.urls import path
from paikuan import views

urlpatterns = [
    path('version', views.version),
    path('register', views.register),
    path('login', views.login),
    path('registration-status', views.registration_status),
    path('me', views.me),
    path('payments', views.payments),
    path('payments/bulk-delete', views.payments_bulk_delete),
    path('payments/bulk-pay', views.payments_bulk_pay),
    path('payments/prepaid-balance', views.prepaid_balance),
    path('payments/template', views.payment_template),
    path('payments/import', views.payment_import),
    path('payments/import/precheck', views.payment_import_precheck),
    path('payments/import/apply', views.payment_import_apply),
    path('payments/export', views.payment_export),
    path('payments/<int:pk>', views.payment_detail),
    path('payments/<int:pk>/logs', views.payment_change_logs),
    path('payments/<int:pk>/offsets', views.payment_offsets),
    path('payments/<int:pk>/plan-items/<int:iid>', views.payment_plan_item_delete),
    path('approvals', views.approval_records),
    path('approvals/bulk-delete', views.approval_records_bulk_delete),
    path('approvals/bulk-approve', views.approval_records_bulk_approve),
    path('approvals/bulk-schedule', views.approval_records_bulk_schedule),
    path('approvals/template', views.approval_template),
    path('approvals/import', views.approval_import),
    path('approvals/import/precheck', views.approval_import_precheck),
    path('approvals/import/apply', views.approval_import_apply),
    path('approvals/export', views.approval_export),
    path('approvals/<int:pk>', views.approval_record_detail),
    path('approvals/<int:pk>/schedule', views.approval_record_schedule),
    path('dashboard', views.dashboard),
    path('stats', views.stats),
    path('users', views.users),
    path('users/<int:pk>', views.user_detail),
    path('users/<int:pk>/approve', views.approve_user),
    path('users/<int:pk>/reject', views.reject_user),
    path('permissions', views.permissions),
    path('permissions/<str:job>', views.permission_detail),
    path('departments', views.departments),
    path('audit-logs', views.audit_logs),
    path('audit-logs/prune', views.audit_logs_prune),
]
